name: "Rigor"
description: "Run Rigor test quality analysis and post PR comment with score and issues"
inputs:
  rigor-version:
    description: "Rigor version tag (e.g. v1.0.4); 'latest' fetches the newest release"
    required: false
    default: "latest"
  comment-threshold:
    description: "Only post comment if average score below this (0-100); 100 = always"
    required: false
    default: "100"
  upload-sarif:
    description: "Upload SARIF for Code Scanning"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Install Rigor
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: enriquesanchez-elastic/rigor
        RIGOR_VERSION: ${{ inputs.rigor-version }}
      run: |
        if command -v rigor >/dev/null 2>&1; then
          echo "rigor: already on PATH ($(rigor --version))"
        else
          echo "rigor: installing from GitHub release..."
          if [ "$RIGOR_VERSION" = "latest" ]; then
            TAG=$(gh release view --repo "$GH_REPO" --json tagName -q .tagName)
          else
            TAG="$RIGOR_VERSION"
          fi
          # Determine asset name based on runner OS/arch
          case "$(uname -s)-$(uname -m)" in
            Linux-x86_64)  ASSET="rigor-linux-x86_64" ;;
            Linux-aarch64) ASSET="rigor-linux-aarch64" ;;
            Darwin-x86_64) ASSET="rigor-macos-x86_64" ;;
            Darwin-arm64)  ASSET="rigor-macos-aarch64" ;;
            *)             echo "::error::Unsupported platform: $(uname -s)-$(uname -m)"; exit 1 ;;
          esac
          gh release download "$TAG" --repo "$GH_REPO" --pattern "$ASSET" --output rigor-bin
          chmod +x rigor-bin
          sudo mv rigor-bin /usr/local/bin/rigor
          echo "rigor: installed $TAG ($ASSET)"
        fi
        # Verify the binary actually works
        rigor --version

    - name: Find changed test files
      id: changed
      shell: bash
      run: |
        # In a PR, diff against the base branch; otherwise fall back to HEAD~1
        if [ -n "$GITHUB_BASE_REF" ]; then
          BASE="origin/$GITHUB_BASE_REF"
        else
          BASE="HEAD~1"
        fi
        echo "rigor: diffing against $BASE"

        # Collect changed test files (added/modified only, not deleted)
        TEST_FILES=$(git diff --name-only --diff-filter=ACM "$BASE"...HEAD -- \
          '*.test.ts' '*.test.tsx' '*.spec.ts' '*.spec.tsx' '*.cy.ts' '*.cy.tsx' \
          '*.test.js' '*.test.jsx' '*.spec.js' '*.spec.jsx' | tr '\n' ' ')

        echo "rigor: changed test files: ${TEST_FILES:-<none>}"
        echo "test_files=$TEST_FILES" >> "$GITHUB_OUTPUT"

    - name: Run Rigor (JSON)
      id: rigor
      shell: bash
      run: |
        TEST_FILES="${{ steps.changed.outputs.test_files }}"

        if [ -z "$TEST_FILES" ]; then
          echo '{"results":[],"summary":{"filesAnalyzed":0,"averageScore":0}}' > rigor-output.json
          echo "rigor: no changed test files to analyze"
          exit 0
        fi

        # Run analysis; exit code 1 = threshold failure (expected), other = real error
        set +e
        rigor $TEST_FILES --json > rigor-output.json
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -eq 0 ] || [ $EXIT_CODE -eq 1 ]; then
          echo "rigor: analysis completed (exit $EXIT_CODE)"
        else
          echo "::error::Rigor analysis failed with exit code $EXIT_CODE"
          cat rigor-output.json || true
          exit $EXIT_CODE
        fi

    - name: Run Rigor (SARIF)
      if: inputs.upload-sarif == 'true'
      shell: bash
      run: |
        TEST_FILES="${{ steps.changed.outputs.test_files }}"

        if [ -z "$TEST_FILES" ]; then
          echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[]}' > rigor.sarif
          exit 0
        fi

        rigor $TEST_FILES --sarif > rigor.sarif || {
          echo "::warning::SARIF generation failed; skipping upload"
          echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[]}' > rigor.sarif
        }

    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          let body = '## Rigor Test Quality\n\n';
          try {
            const raw = fs.readFileSync('rigor-output.json', 'utf8');
            const data = JSON.parse(raw);
            const results = data.results || (Array.isArray(data) ? data : []);
            const summary = data.summary || {};
            if (results.length === 0 && !summary.filesAnalyzed) {
              body += 'No test files changed in this PR.\n';
            } else {
              results.forEach(r => {
                const s = r.score?.value ?? 0;
                const g = r.score?.grade ?? '';
                body += `- **${r.filePath || r.file_path || '?'}**: ${s}/100 (${g})\n`;
              });
              const avg = summary.averageScore ?? (results.reduce((a, r) => a + (r.score?.value ?? 0), 0) / (results.length || 1));
              body += `\n**Average score:** ${Math.round(avg)}/100\n`;
            }
            body += '\n_Powered by [Rigor](https://github.com/rigor-dev/rigor)_';
          } catch (e) {
            body += `⚠️ Rigor output could not be parsed: ${e.message}\n`;
            body += 'Run `rigor --json --changed` locally to debug.\n';
          }
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          });

    - name: Upload SARIF
      if: inputs.upload-sarif == 'true'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: rigor.sarif
      continue-on-error: true
